using System.IO; using System.Net.Http; using System.Windows; using DocumentFormat.OpenXml.Packaging; using DocumentFormat.OpenXml.Wordprocessing; using NAudio.Wave; using Whisper.net;
namespace DanishTranscriber;
public partial class MainWindow : Window {
 WaveInEvent? mic; MemoryStream? audio; CancellationTokenSource? cts; string? docxPath; readonly SemaphoreSlim saveLock=new(1,1);
 readonly string appDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DanishTranscriber");
 string ModelPath=>Path.Combine(appDir,"ggml-small.bin");
 public MainWindow()=>InitializeComponent();
 async void Start_Click(object s,RoutedEventArgs e){try{StartButton.IsEnabled=false;TranscriptBox.Clear();Directory.CreateDirectory(appDir);await EnsureModelAsync();var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Danish Transcripts");Directory.CreateDirectory(d);docxPath=Path.Combine(d,$"{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.docx");await SaveDocxAsync();audio=new MemoryStream();mic=new WaveInEvent{WaveFormat=new WaveFormat(16000,16,1),BufferMilliseconds=100};mic.DataAvailable+=(_,a)=>{lock(audio)audio.Write(a.Buffer,0,a.BytesRecorded);};mic.StartRecording();cts=new();StopButton.IsEnabled=true;StatusText.Text="Listening • local/offline transcription";_=Loop(cts.Token);}catch(Exception ex){StartButton.IsEnabled=true;StatusText.Text="Error";MessageBox.Show(ex.ToString(),"Could not start");}}
 async Task EnsureModelAsync(){if(File.Exists(ModelPath))return;StatusText.Text="First run: downloading Whisper small model (~466 MB)…";using var h=new HttpClient{Timeout=TimeSpan.FromHours(1)};using var r=await h.GetAsync("https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",HttpCompletionOption.ResponseHeadersRead);r.EnsureSuccessStatusCode();await using var x=await r.Content.ReadAsStreamAsync();await using var f=File.Create(ModelPath);await x.CopyToAsync(f);}
 async Task Loop(CancellationToken t){long done=0;while(!t.IsCancellationRequested){await Task.Delay(12000,t);byte[] pcm;lock(audio!){var all=audio!.ToArray();if(all.Length<=done)continue;pcm=all[(int)done..];done=all.Length;}if(pcm.Length<64000)continue;StatusText.Text="Transcribing locally…";var wav=BuildWav(pcm);using var factory=WhisperFactory.FromPath(ModelPath);using var p=factory.CreateBuilder().WithLanguage("da").Build();await using var ms=new MemoryStream(wav);var parts=new List<string>();await foreach(var seg in p.ProcessAsync(ms,t))if(!string.IsNullOrWhiteSpace(seg.Text))parts.Add(seg.Text.Trim());if(parts.Count>0){TranscriptBox.AppendText((TranscriptBox.Text.Length>0?" ":"")+string.Join(" ",parts));TranscriptBox.ScrollToEnd();await SaveDocxAsync();}StatusText.Text="Listening";}}
 async void Stop_Click(object s,RoutedEventArgs e){cts?.Cancel();mic?.StopRecording();mic?.Dispose();mic=null;await SaveDocxAsync();StatusText.Text=$"Saved: {docxPath}";StopButton.IsEnabled=false;StartButton.IsEnabled=true;}
 async Task SaveDocxAsync(){if(docxPath is null)return;await saveLock.WaitAsync();try{var tmp=docxPath+".tmp";using(var doc=WordprocessingDocument.Create(tmp,DocumentFormat.OpenXml.WordprocessingDocumentType.Document)){var m=doc.AddMainDocumentPart();m.Document=new Document(new Body(new Paragraph(new Run(new Text($"Danish transcript — {DateTime.Now:yyyy-MM-dd HH:mm}"))),new Paragraph(new Run(new Text(TranscriptBox.Text??""){Space=DocumentFormat.OpenXml.SpaceProcessingModeValues.Preserve}))));m.Document.Save();}File.Move(tmp,docxPath,true);}finally{saveLock.Release();}}
 void Clear_Click(object s,RoutedEventArgs e)=>TranscriptBox.Clear(); void Copy_Click(object s,RoutedEventArgs e){if(!string.IsNullOrEmpty(TranscriptBox.Text))Clipboard.SetText(TranscriptBox.Text);}
 protected override void OnClosed(EventArgs e){cts?.Cancel();mic?.StopRecording();mic?.Dispose();base.OnClosed(e);}
 static byte[] BuildWav(byte[] pcm){using var m=new MemoryStream();using(var w=new BinaryWriter(m,System.Text.Encoding.UTF8,true)){w.Write(System.Text.Encoding.ASCII.GetBytes("RIFF"));w.Write(36+pcm.Length);w.Write(System.Text.Encoding.ASCII.GetBytes("WAVEfmt "));w.Write(16);w.Write((short)1);w.Write((short)1);w.Write(16000);w.Write(32000);w.Write((short)2);w.Write((short)16);w.Write(System.Text.Encoding.ASCII.GetBytes("data"));w.Write(pcm.Length);w.Write(pcm);}return m.ToArray();}
}